POST http://localhost:81/user/register
Content-Type: application/json

{
  "id": 0,
  "password": "123456",
  "phone": "13027378933",
  "name": "admin",
  "userType": 1,
  "score": 0
}

###

POST http://localhost:81/user/login
Content-Type: application/json

{
  "password": "123456",
  "phone": "13027378933"
}
###

#查询志愿者管理的儿童信息
GET http://localhost:81/user/queryChildren/1719571781871759360?currentPage=1&pageSize=5
Accept: application/json


#绑定
###
PUT http://localhost:81/user/bindChild?volunteerId=1719571781871759360&childId=1719571666675200000
Content-Type: application/json

###

#接触绑定
PUT http://localhost:81/user/disBindChild?childId=1719571666675200000
Content-Type: application/json



###