spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dreams?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: "root"
    password: "20030405zzR"
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 81

mybatis-plus:
  #  typeAliasesPackage: pers.lxl.myonlineclass.model.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true #开启驼峰下划线转换
    cacheEnabled: true #开启二级缓存
    lazy-loading-enabled: true #开启懒加载
    aggressive-lazy-loading: false #关闭按需加载
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启控制台打印sql



